### ISSUE TITLE
Could not find header file: limits.h given context, trying to operate on libcurl

### ISSUE THREAD

**Issue by cayolblake** [ircmaxell/FFIMe#13]
Hi @ircmaxell 

Running the following code, not necessarily on this specific version of libcurl, but other versions on different Linux distros as well.

```
<?php
require __DIR__ . '/vendor/autoload.php';
(new FFIMe\FFIMe("/usr/lib64/libcurl.so.4.7.0"))
    ->include("/usr/include/curl/curl.h")
    ->codeGen('curl\\curl', __DIR__ . '/curl.php');
require __DIR__ . '/curl.php';
$libc = new curl\curl;
//$libc->printf("test\n");
```

I am getting the following, and here's the exact curl.h file I currently have https://github.com/curl/curl/blob/curl-7_82_0/include/curl/curl.h

```
array(6) {
  [0]=>
  string(18) "/usr/local/include"
  [1]=>
  string(12) "/usr/include"
  [2]=>
  string(29) "/usr/include/x86_64-linux-gnu"
  [3]=>
  string(107) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
  [4]=>
  string(157) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/"
  [5]=>
  string(40) "/usr/lib/gcc/x86_64-linux-gnu/12/include"
}
PHP Fatal error:  Uncaught LogicException: Could not find header file: limits.h given context /usr/include (called from /usr/include/limits.h) in ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php:267
Stack trace:
#0 ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(219): PHPCParser\PreProcessor->findHeaderFile()
#1 ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(256): PHPCParser\PreProcessor->findAndParse()
#2 ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(60): PHPCParser\PreProcessor->resolveInclude()
#3 ~/vendor/ircmaxell/php-c-parser/lib/CParser.php(23): PHPCParser\PreProcessor->process()
#4 ~/vendor/ircmaxell/ffime/lib/FFIMe.php(113): PHPCParser\CParser->parse()
#5 ~/test2.php(4): FFIMe\FFIMe->include()
#6 {main}
  thrown in ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php on line 267
```

I tried to lookup for where limits.h exists on my system, and this was the result.

```
/usr/include/limits.h
/usr/include/c++/12/tr1/limits.h
/usr/include/linux/limits.h
/usr/lib/gcc/x86_64-linux-gnu/12/include-fixed/limits.h
/usr/lib/gcc/x86_64-linux-gnu/12/install-tools/include/limits.h
/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h
```

Not sure why there's an issue with limits.h. 

Any idea what am I doing wrong?

**Comment by bwoebi** [comment]
I can reproduce the issue, checking it out. (we need to improve upon our error reporting too)

**Comment by cayolblake** [comment]
Thanks @bwoebi 

Our team is starting to adopt PHP FFI so your library will help a lot and perhaps at a certain stage of having confidence we can start contributing after reading more on how it operates internally.

I believe the future is for PHP FFI.

Awaiting your fix :)

**Comment by bwoebi** [comment]
The issue has been fixed via https://github.com/ircmaxell/php-c-parser/commit/508399199fc87418888eae235db9967ada51f701 (and found another issue in this library, fixed as well)

**Comment by bwoebi** [comment]
Btw. the focus with this library currently is improving its ergonomics when using the generated code (and possibly implementing missing features if there are any). It should be easy and intuitive to use.

Any feedback you have is welcome @cayolblake :-)

**Comment by cayolblake** [comment]
@bwoebi 

I ran `composer update` and made sure all libraries are at latest commit, yet still having the same issue. I even opened all changed files and verified they got the latest changes.

```
array(6) {
  [0]=>
  string(18) "/usr/local/include"
  [1]=>
  string(12) "/usr/include"
  [2]=>
  string(29) "/usr/include/x86_64-linux-gnu"
  [3]=>
  string(107) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
  [4]=>
  string(157) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/"
  [5]=>
  string(40) "/usr/lib/gcc/x86_64-linux-gnu/12/include"
}
PHP Fatal error:  Uncaught LogicException: Could not find header file: limits.h given context /usr/include (called from /usr/include/limits.h) in ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php:268
Stack trace:
#0 ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(220): PHPCParser\PreProcessor->findHeaderFile()
#1 ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(257): PHPCParser\PreProcessor->findAndParse()
#2 ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(60): PHPCParser\PreProcessor->resolveInclude()
#3 ~/vendor/ircmaxell/php-c-parser/lib/CParser.php(23): PHPCParser\PreProcessor->process()
#4 ~/vendor/ircmaxell/ffime/lib/FFIMe.php(113): PHPCParser\CParser->parse()
#5 ~/curl-wrapper.php(6): FFIMe\FFIMe->include()
#6 {main}
  thrown in ~/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php on line 268
```

**Comment by bwoebi** [comment]
Weird, it works for me now, i.e. cannot reproduce the issue with current ircmaxell/php-c-parser on dev-master.

**Comment by cayolblake** [comment]
@bwoebi I'll create a new project and retry in a moment.

**Comment by cayolblake** [comment]
@bwoebi 

Same issue persists.

`composer.json`

```
{
    "require": {
        "ircmaxell/php-object-symbolresolver": "dev-master",
        "ircmaxell/ffime": "dev-master",
        "ircmaxell/php-c-parser": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

`ffime-test.php`
```
<?php
require __DIR__ . '/vendor/autoload.php';
(new FFIMe\FFIMe("/usr/lib64/libcurl.so.4.7.0"))
    ->include("/usr/include/curl/curl.h")
    ->codeGen('curl\\curl', __DIR__ . '/curl.php');
require __DIR__ . '/curl.php';
$libc = new curl\curl;
//$libc->printf("test\n");
```

`error output`
```
array(6) {
  [0]=>
  string(18) "/usr/local/include"
  [1]=>
  string(12) "/usr/include"
  [2]=>
  string(29) "/usr/include/x86_64-linux-gnu"
  [3]=>
  string(107) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
  [4]=>
  string(157) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/"
  [5]=>
  string(40) "/usr/lib/gcc/x86_64-linux-gnu/12/include"
}
PHP Fatal error:  Uncaught LogicException: Could not find header file: limits.h given context /usr/include (called from /usr/include/limits.h) in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php:275
Stack trace:
#0 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(220): PHPCParser\PreProcessor->findHeaderFile()
#1 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(261): PHPCParser\PreProcessor->findAndParse()
#2 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(60): PHPCParser\PreProcessor->resolveInclude()
#3 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/CParser.php(23): PHPCParser\PreProcessor->process()
#4 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/ffime/lib/FFIMe.php(113): PHPCParser\CParser->parse()
#5 ~/test-20220814-1030PM-CEST/ffime-test.php(4): FFIMe\FFIMe->include()
#6 {main}
  thrown in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php on line 275
```

I went further to try to debug inside the `vendor/ircmaxell/php-c-parser/lib/PreProcessor.php` file, and added a log inside `findHeaderFile` function just before `return $headerFile`, and another just before the `var_dump`, and here's what I got.

```
DEBUG: /usr/include/curl/curl.h, , .
DEBUG: curlver.h, /usr/include/curl, /usr/include/curl/curl.h.
DEBUG: system.h, /usr/include/curl, /usr/include/curl/curl.h.
DEBUG: sys/types.h, /usr/include/curl, /usr/include/curl/system.h.
DEBUG: features.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: features-time64.h, /usr/include, /usr/include/features.h.
DEBUG: bits/wordsize.h, /usr/include, /usr/include/features-time64.h.
DEBUG: bits/timesize.h, /usr/include, /usr/include/features-time64.h.
DEBUG: bits/wordsize.h, /usr/include/bits, /usr/include/bits/timesize.h.
DEBUG: stdc-predef.h, /usr/include, /usr/include/features.h.
DEBUG: sys/cdefs.h, /usr/include, /usr/include/features.h.
DEBUG: bits/wordsize.h, /usr/include/sys, /usr/include/sys/cdefs.h.
DEBUG: bits/long-double.h, /usr/include/sys, /usr/include/sys/cdefs.h.
DEBUG: gnu/stubs.h, /usr/include, /usr/include/features.h.
DEBUG: gnu/stubs-64.h, /usr/include/gnu, /usr/include/gnu/stubs.h.
DEBUG: bits/types.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: features.h, /usr/include/bits, /usr/include/bits/types.h.
DEBUG: bits/wordsize.h, /usr/include/bits, /usr/include/bits/types.h.
DEBUG: bits/timesize.h, /usr/include/bits, /usr/include/bits/types.h.
DEBUG: bits/wordsize.h, /usr/include/bits, /usr/include/bits/timesize.h.
DEBUG: bits/typesizes.h, /usr/include/bits, /usr/include/bits/types.h.
DEBUG: bits/time64.h, /usr/include/bits, /usr/include/bits/types.h.
DEBUG: bits/types/clock_t.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/clock_t.h.
DEBUG: bits/types/clockid_t.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/clockid_t.h.
DEBUG: bits/types/time_t.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/time_t.h.
DEBUG: bits/types/timer_t.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/timer_t.h.
DEBUG: stddef.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: bits/stdint-intn.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: bits/types.h, /usr/include/bits, /usr/include/bits/stdint-intn.h.
DEBUG: endian.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: features.h, /usr/include, /usr/include/endian.h.
DEBUG: bits/endian.h, /usr/include, /usr/include/endian.h.
DEBUG: bits/endianness.h, /usr/include/bits, /usr/include/bits/endian.h.
DEBUG: bits/byteswap.h, /usr/include, /usr/include/endian.h.
DEBUG: features.h, /usr/include/bits, /usr/include/bits/byteswap.h.
DEBUG: bits/types.h, /usr/include/bits, /usr/include/bits/byteswap.h.
DEBUG: bits/uintn-identity.h, /usr/include, /usr/include/endian.h.
DEBUG: bits/types.h, /usr/include/bits, /usr/include/bits/uintn-identity.h.
DEBUG: sys/select.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: features.h, /usr/include/sys, /usr/include/sys/select.h.
DEBUG: bits/types.h, /usr/include/sys, /usr/include/sys/select.h.
DEBUG: bits/select.h, /usr/include/sys, /usr/include/sys/select.h.
DEBUG: bits/types/sigset_t.h, /usr/include/sys, /usr/include/sys/select.h.
DEBUG: bits/types/__sigset_t.h, /usr/include/bits/types, /usr/include/bits/types/sigset_t.h.
DEBUG: bits/types/time_t.h, /usr/include/sys, /usr/include/sys/select.h.
DEBUG: bits/types/struct_timeval.h, /usr/include/sys, /usr/include/sys/select.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/struct_timeval.h.
DEBUG: bits/types/struct_timespec.h, /usr/include/sys, /usr/include/sys/select.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/struct_timespec.h.
DEBUG: bits/endian.h, /usr/include/bits/types, /usr/include/bits/types/struct_timespec.h.
DEBUG: bits/types/time_t.h, /usr/include/bits/types, /usr/include/bits/types/struct_timespec.h.
DEBUG: bits/pthreadtypes.h, /usr/include/sys, /usr/include/sys/types.h.
DEBUG: bits/thread-shared-types.h, /usr/include/bits, /usr/include/bits/pthreadtypes.h.
DEBUG: bits/pthreadtypes-arch.h, /usr/include/bits, /usr/include/bits/thread-shared-types.h.
DEBUG: bits/wordsize.h, /usr/include/bits, /usr/include/bits/pthreadtypes-arch.h.
DEBUG: bits/atomic_wide_counter.h, /usr/include/bits, /usr/include/bits/thread-shared-types.h.
DEBUG: bits/struct_mutex.h, /usr/include/bits, /usr/include/bits/thread-shared-types.h.
DEBUG: bits/struct_rwlock.h, /usr/include/bits, /usr/include/bits/thread-shared-types.h.
DEBUG: sys/socket.h, /usr/include/curl, /usr/include/curl/system.h.
DEBUG: features.h, /usr/include/sys, /usr/include/sys/socket.h.
DEBUG: bits/types/struct_iovec.h, /usr/include/sys, /usr/include/sys/socket.h.
DEBUG: stddef.h, /usr/include/bits/types, /usr/include/bits/types/struct_iovec.h.
DEBUG: stddef.h, /usr/include/sys, /usr/include/sys/socket.h.
DEBUG: bits/socket.h, /usr/include/sys, /usr/include/sys/socket.h.
DEBUG: stddef.h, /usr/include/bits, /usr/include/bits/socket.h.
DEBUG: sys/types.h, /usr/include/bits, /usr/include/bits/socket.h.
DEBUG: bits/socket_type.h, /usr/include/bits, /usr/include/bits/socket.h.
DEBUG: bits/sockaddr.h, /usr/include/bits, /usr/include/bits/socket.h.
DEBUG: bits/types/time_t.h, /usr/include/bits, /usr/include/bits/socket.h.
DEBUG: asm/socket.h, /usr/include/bits, /usr/include/bits/socket.h.
DEBUG: asm-generic/socket.h, /usr/include/asm, /usr/include/asm/socket.h.
DEBUG: linux/posix_types.h, /usr/include/asm-generic, /usr/include/asm-generic/socket.h.
DEBUG: linux/stddef.h, /usr/include/linux, /usr/include/linux/posix_types.h.
DEBUG: asm/posix_types.h, /usr/include/linux, /usr/include/linux/posix_types.h.
DEBUG: asm/posix_types_64.h, /usr/include/asm, /usr/include/asm/posix_types.h.
DEBUG: asm-generic/posix_types.h, /usr/include/asm, /usr/include/asm/posix_types_64.h.
DEBUG: asm/bitsperlong.h, /usr/include/asm-generic, /usr/include/asm-generic/posix_types.h.
DEBUG: asm-generic/bitsperlong.h, /usr/include/asm, /usr/include/asm/bitsperlong.h.
DEBUG: asm/sockios.h, /usr/include/asm-generic, /usr/include/asm-generic/socket.h.
DEBUG: asm-generic/sockios.h, /usr/include/asm, /usr/include/asm/sockios.h.
DEBUG: bits/types/struct_osockaddr.h, /usr/include/sys, /usr/include/sys/socket.h.
DEBUG: stdio.h, /usr/include/curl, /usr/include/curl/curl.h.
DEBUG: bits/libc-header-start.h, /usr/include, /usr/include/stdio.h.
DEBUG: features.h, /usr/include/bits, /usr/include/bits/libc-header-start.h.
DEBUG: stddef.h, /usr/include, /usr/include/stdio.h.
DEBUG: stdarg.h, /usr/include, /usr/include/stdio.h.
DEBUG: bits/types.h, /usr/include, /usr/include/stdio.h.
DEBUG: bits/types/__fpos_t.h, /usr/include, /usr/include/stdio.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/__fpos_t.h.
DEBUG: bits/types/__mbstate_t.h, /usr/include/bits/types, /usr/include/bits/types/__fpos_t.h.
DEBUG: bits/types/__fpos64_t.h, /usr/include, /usr/include/stdio.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/__fpos64_t.h.
DEBUG: bits/types/__mbstate_t.h, /usr/include/bits/types, /usr/include/bits/types/__fpos64_t.h.
DEBUG: bits/types/__FILE.h, /usr/include, /usr/include/stdio.h.
DEBUG: bits/types/FILE.h, /usr/include, /usr/include/stdio.h.
DEBUG: bits/types/struct_FILE.h, /usr/include, /usr/include/stdio.h.
DEBUG: bits/types.h, /usr/include/bits/types, /usr/include/bits/types/struct_FILE.h.
DEBUG: bits/stdio_lim.h, /usr/include, /usr/include/stdio.h.
DEBUG: bits/floatn.h, /usr/include, /usr/include/stdio.h.
DEBUG: features.h, /usr/include/bits, /usr/include/bits/floatn.h.
DEBUG: bits/floatn-common.h, /usr/include/bits, /usr/include/bits/floatn.h.
DEBUG: features.h, /usr/include/bits, /usr/include/bits/floatn-common.h.
DEBUG: bits/long-double.h, /usr/include/bits, /usr/include/bits/floatn-common.h.
DEBUG: limits.h, /usr/include/curl, /usr/include/curl/curl.h.
DEBUG: bits/libc-header-start.h, /usr/include, /usr/include/limits.h.
DEBUG: features.h, /usr/include/bits, /usr/include/bits/libc-header-start.h.
** ERROR: limits.h, /usr/include, /usr/include/limits.h.
array(6) {
  [0]=>
  string(18) "/usr/local/include"
  [1]=>
  string(12) "/usr/include"
  [2]=>
  string(29) "/usr/include/x86_64-linux-gnu"
  [3]=>
  string(107) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
  [4]=>
  string(157) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/"
  [5]=>
  string(40) "/usr/lib/gcc/x86_64-linux-gnu/12/include"
}
PHP Fatal error:  Uncaught LogicException: Could not find header file: limits.h given context /usr/include (called from /usr/include/limits.h) in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php:275
Stack trace:
#0 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(220): PHPCParser\PreProcessor->findHeaderFile()
#1 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(261): PHPCParser\PreProcessor->findAndParse()
#2 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(60): PHPCParser\PreProcessor->resolveInclude()
#3 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/CParser.php(23): PHPCParser\PreProcessor->process()
#4 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/ffime/lib/FFIMe.php(113): PHPCParser\CParser->parse()
#5 ~/test-20220814-1030PM-CEST/ffime-test.php(4): FFIMe\FFIMe->include()
#6 {main}
  thrown in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php on line 275
```

Hopefully this would help nailing it down 🤔 ?!

**Comment by bwoebi** [comment]
The instruction at which it fails should be `#include_next "limits.h"` - meaning it searches in a directory in the list of include paths after the current `$contextDir`.

I suppose the order of inclusions is wrong here.

According to gcc the order should be:
```
 /usr/lib/gcc/x86_64-linux-gnu/11/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
```

I have gcc 11, you have gcc 12, maybe that's why we had a difference between our outputs. I'll correct the order.

**Comment by cayolblake** [comment]
Looping on checking the list you provided, I just get the following.
```
/usr/lib/gcc/x86_64-linux-gnu/11/include: cannot open `/usr/lib/gcc/x86_64-linux-gnu/11/include' (No such file or directory)

/usr/local/include: directory

/usr/include/x86_64-linux-gnu: cannot open `/usr/include/x86_64-linux-gnu' (No such file or directory)

/usr/include: directory
```

And yeah, I do have `/usr/lib/gcc/x86_64-linux-gnu/12/include`

**Comment by cayolblake** [comment]
@bwoebi I see applied an update, and here's the result after `composer update`

```
array(6) {
  [0]=>
  string(40) "/usr/lib/gcc/x86_64-linux-gnu/12/include"
  [1]=>
  string(18) "/usr/local/include"
  [2]=>
  string(29) "/usr/include/x86_64-linux-gnu"
  [3]=>
  string(12) "/usr/include"
  [4]=>
  string(107) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
  [5]=>
  string(157) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/"
}
PHP Fatal error:  Uncaught LogicException: Could not find header file: limits.h given context /usr/include (called from /usr/include/limits.h) in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php:268
Stack trace:
#0 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(220): PHPCParser\PreProcessor->findHeaderFile()
#1 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(257): PHPCParser\PreProcessor->findAndParse()
#2 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(60): PHPCParser\PreProcessor->resolveInclude()
#3 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/CParser.php(23): PHPCParser\PreProcessor->process()
#4 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/ffime/lib/FFIMe.php(113): PHPCParser\CParser->parse()
#5 ~/test-20220814-1030PM-CEST/ffime-test.php(4): FFIMe\FFIMe->include()
#6 {main}
  thrown in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php on line 268
```

**Comment by bwoebi** [comment]
Yep, there's yet another thing going on, with the _correct_ include order it's now also failing for me. I'll have to investigate. I'll do it tomorrow.

**Comment by cayolblake** [comment]
👍

**Comment by bwoebi** [comment]
Hey @cayolblake I've found it: https://github.com/ircmaxell/php-c-parser/commit/b6a5f472e659aecb82e50c2933ac3386b234fa0e - it's been a subtle difference in how `#include <>` and `#include ""` directives are handled.

**Comment by cayolblake** [comment]
@bwoebi let me try it now and verify back.

Thanks anyways 😊

**Comment by cayolblake** [comment]
@bwoebi darn, its still there after update.

```
array(6) {
  [0]=>
  string(40) "/usr/lib/gcc/x86_64-linux-gnu/12/include"
  [1]=>
  string(18) "/usr/local/include"
  [2]=>
  string(29) "/usr/include/x86_64-linux-gnu"
  [3]=>
  string(12) "/usr/include"
  [4]=>
  string(107) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
  [5]=>
  string(157) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/"
}
PHP Fatal error:  Uncaught LogicException: Could not find header file: limits.h given context /usr/include (called from /usr/include/limits.h) in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php:268
Stack trace:
#0 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(220): PHPCParser\PreProcessor->findHeaderFile()
#1 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(257): PHPCParser\PreProcessor->findAndParse()
#2 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(60): PHPCParser\PreProcessor->resolveInclude()
#3 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/CParser.php(23): PHPCParser\PreProcessor->process()
#4 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/ffime/lib/FFIMe.php(113): PHPCParser\CParser->parse()
#5 ~/test-20220814-1030PM-CEST/ffime-test.php(4): FFIMe\FFIMe->include()
#6 {main}
  thrown in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php on line 268
```

**Comment by bwoebi** [comment]
I have two questions for you: what's the output of `echo "#include <limits.h>" | gcc -E -xc -v - | grep limits`

And, what's the output when you add var_dump()'s to https://github.com/ircmaxell/php-c-parser/blob/b6a5f472e659aecb82e50c2933ac3386b234fa0e/lib/PreProcessor.php#L263 - and dump $contextDir and the found header name.

At least for me it works now, again :-/

**Comment by cayolblake** [comment]
For the first question, here you go.

```
$ echo "#include <limits.h>" | gcc -E -xc -v - | grep limits

Using built-in specs.
COLLECT_GCC=gcc
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-libstdcxx-backtrace --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-12.1.1-20220507/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-offload-defaulted --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.1 20220507 (Red Hat 12.1.1-1) (GCC)
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/12/cc1 -E -quiet -v - -mtune=generic -march=x86-64 -dumpbase -
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/12/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/12/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/12/include
 /usr/local/include
 /usr/include
End of search list.
# 1 "/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h" 1 3 4
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/12/:/usr/libexec/gcc/x86_64-redhat-linux/12/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/12/:/usr/lib/gcc/x86_64-redhat-linux/
# 34 "/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h" 3 4
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/12/:/usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/12/../../../:/lib/:/usr/lib/
# 1 "/usr/lib/gcc/x86_64-redhat-linux/12/include/syslimits.h" 1 3 4
# 1 "/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h" 1 3 4
# 203 "/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h" 3 4
# 1 "/usr/include/limits.h" 1 3 4
# 26 "/usr/include/limits.h" 3 4
# 27 "/usr/include/limits.h" 2 3 4
# 195 "/usr/include/limits.h" 3 4
# 1 "/usr/include/linux/limits.h" 1 3 4
# 196 "/usr/include/limits.h" 2 3 4
# 200 "/usr/include/limits.h" 2 3 4
# 204 "/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h" 2 3 4
# 8 "/usr/lib/gcc/x86_64-redhat-linux/12/include/syslimits.h" 2 3 4
# 35 "/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h" 2 3 4
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
```

**Comment by cayolblake** [comment]
And the second here.

```
$header -> /usr/include/curl/curl.h, $contextDir ->
$header -> curlver.h, $contextDir -> /usr/include/curl
$header -> system.h, $contextDir -> /usr/include/curl
$header -> sys/types.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> features-time64.h, $contextDir ->
$header -> bits/wordsize.h, $contextDir ->
$header -> bits/timesize.h, $contextDir ->
$header -> bits/wordsize.h, $contextDir ->
$header -> stdc-predef.h, $contextDir ->
$header -> sys/cdefs.h, $contextDir ->
$header -> bits/wordsize.h, $contextDir ->
$header -> bits/long-double.h, $contextDir ->
$header -> gnu/stubs.h, $contextDir ->
$header -> gnu/stubs-64.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> bits/wordsize.h, $contextDir ->
$header -> bits/timesize.h, $contextDir ->
$header -> bits/wordsize.h, $contextDir ->
$header -> bits/typesizes.h, $contextDir ->
$header -> bits/time64.h, $contextDir ->
$header -> bits/types/clock_t.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/types/clockid_t.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/types/time_t.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/types/timer_t.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> stddef.h, $contextDir ->
$header -> bits/stdint-intn.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> endian.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> bits/endian.h, $contextDir ->
$header -> bits/endianness.h, $contextDir ->
$header -> bits/byteswap.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/uintn-identity.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> sys/select.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/select.h, $contextDir ->
$header -> bits/types/sigset_t.h, $contextDir ->
$header -> bits/types/__sigset_t.h, $contextDir ->
$header -> bits/types/time_t.h, $contextDir ->
$header -> bits/types/struct_timeval.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/types/struct_timespec.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/endian.h, $contextDir ->
$header -> bits/types/time_t.h, $contextDir ->
$header -> bits/pthreadtypes.h, $contextDir ->
$header -> bits/thread-shared-types.h, $contextDir ->
$header -> bits/pthreadtypes-arch.h, $contextDir ->
$header -> bits/wordsize.h, $contextDir ->
$header -> bits/atomic_wide_counter.h, $contextDir ->
$header -> bits/struct_mutex.h, $contextDir ->
$header -> bits/struct_rwlock.h, $contextDir ->
$header -> sys/socket.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> bits/types/struct_iovec.h, $contextDir ->
$header -> stddef.h, $contextDir ->
$header -> stddef.h, $contextDir ->
$header -> bits/socket.h, $contextDir ->
$header -> stddef.h, $contextDir ->
$header -> sys/types.h, $contextDir ->
$header -> bits/socket_type.h, $contextDir ->
$header -> bits/sockaddr.h, $contextDir ->
$header -> bits/types/time_t.h, $contextDir ->
$header -> asm/socket.h, $contextDir ->
$header -> asm-generic/socket.h, $contextDir ->
$header -> linux/posix_types.h, $contextDir ->
$header -> linux/stddef.h, $contextDir ->
$header -> asm/posix_types.h, $contextDir ->
$header -> asm/posix_types_64.h, $contextDir ->
$header -> asm-generic/posix_types.h, $contextDir ->
$header -> asm/bitsperlong.h, $contextDir ->
$header -> asm-generic/bitsperlong.h, $contextDir ->
$header -> asm/sockios.h, $contextDir ->
$header -> asm-generic/sockios.h, $contextDir ->
$header -> bits/types/struct_osockaddr.h, $contextDir ->
$header -> stdio.h, $contextDir ->
$header -> bits/libc-header-start.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> stddef.h, $contextDir ->
$header -> stdarg.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/types/__fpos_t.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/types/__mbstate_t.h, $contextDir ->
$header -> bits/types/__fpos64_t.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/types/__mbstate_t.h, $contextDir ->
$header -> bits/types/__FILE.h, $contextDir ->
$header -> bits/types/FILE.h, $contextDir ->
$header -> bits/types/struct_FILE.h, $contextDir ->
$header -> bits/types.h, $contextDir ->
$header -> bits/stdio_lim.h, $contextDir ->
$header -> bits/floatn.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> bits/floatn-common.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> bits/long-double.h, $contextDir ->
$header -> limits.h, $contextDir ->
$header -> bits/libc-header-start.h, $contextDir ->
$header -> features.h, $contextDir ->
$header -> limits.h, $contextDir -> /usr/include
array(6) {
  [0]=>
  string(40) "/usr/lib/gcc/x86_64-linux-gnu/12/include"
  [1]=>
  string(18) "/usr/local/include"
  [2]=>
  string(29) "/usr/include/x86_64-linux-gnu"
  [3]=>
  string(12) "/usr/include"
  [4]=>
  string(107) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
  [5]=>
  string(157) "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/"
}
PHP Fatal error:  Uncaught LogicException: Could not find header file: limits.h given context /usr/include (called from /usr/include/limits.h) in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php:269
Stack trace:
#0 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(220): PHPCParser\PreProcessor->findHeaderFile()
#1 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(257): PHPCParser\PreProcessor->findAndParse()
#2 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(60): PHPCParser\PreProcessor->resolveInclude()
#3 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/CParser.php(23): PHPCParser\PreProcessor->process()
#4 ~/test-20220814-1030PM-CEST/vendor/ircmaxell/ffime/lib/FFIMe.php(113): PHPCParser\CParser->parse()
#5 ~/test-20220814-1030PM-CEST/ffime-test.php(4): FFIMe\FFIMe->include()
#6 {main}
  thrown in ~/test-20220814-1030PM-CEST/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php on line 269
```

Its weird that there's a lookup for limits.h also before that and it doesn't have the $contextDir set, and once it got set it failed.

**Comment by bwoebi** [comment]
I see a `/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h` in your output. I wonder, does `/usr/lib/gcc/x86_64-linux-gnu/12/include/limits.h` even exist on your system?

**Comment by cayolblake** [comment]
No, `/usr/lib/gcc/x86_64-linux-gnu/12/include/limits.h` doesn't exist. Check below.

`updatedb && locate limits.h|grep -v '/home/'|grep '/limits.h'`
```
/usr/include/limits.h
/usr/include/c++/12/tr1/limits.h
/usr/include/linux/limits.h
/usr/lib/gcc/x86_64-linux-gnu/12/include-fixed/limits.h
/usr/lib/gcc/x86_64-linux-gnu/12/install-tools/include/limits.h
/usr/lib/gcc/x86_64-redhat-linux/12/include/limits.h
```

**Comment by bwoebi** [comment]
Okay, then that's our problem, let me include more search paths.

**Comment by bwoebi** [comment]
@cayolblake https://github.com/ircmaxell/php-c-parser/commit/c9267193fdfd1230b5a733622363a479ae53c313 Can you check whether this works?

**Comment by cayolblake** [comment]
@bwoebi Can't believe I'm saying this. It worked! :)

`curl.php` file generated, yet I got the following warnings. These seems like core functions which definitely are there, so may be there's another issue its not finding them.

```
[Warning] Skipping select, not found in object file
[Warning] Skipping pselect, not found in object file
[Warning] Skipping __cmsg_nxthdr, not found in object file
[Warning] Skipping sendmsg, not found in object file
[Warning] Skipping recvmsg, not found in object file
[Warning] Skipping shutdown, not found in object file
[Warning] Skipping sockatmark, not found in object file
[Warning] Skipping isfdtype, not found in object file
[Warning] Skipping remove, not found in object file
[Warning] Skipping renameat, not found in object file
[Warning] Skipping tmpfile, not found in object file
[Warning] Skipping tmpnam, not found in object file
[Warning] Skipping tmpnam_r, not found in object file
[Warning] Skipping tempnam, not found in object file
[Warning] Skipping fflush_unlocked, not found in object file
[Warning] Skipping freopen, not found in object file
[Warning] Skipping fmemopen, not found in object file
[Warning] Skipping open_memstream, not found in object file
[Warning] Skipping setbuf, not found in object file
[Warning] Skipping setbuffer, not found in object file
[Warning] Skipping setlinebuf, not found in object file
[Warning] Skipping fprintf, not found in object file
[Warning] Skipping printf, not found in object file
[Warning] Skipping sprintf, not found in object file
[Warning] Skipping vfprintf, not found in object file
[Warning] Skipping vprintf, not found in object file
[Warning] Skipping vsprintf, not found in object file
[Warning] Skipping snprintf, not found in object file
[Warning] Skipping vsnprintf, not found in object file
[Warning] Skipping vdprintf, not found in object file
[Warning] Skipping dprintf, not found in object file
[Warning] Skipping fscanf, not found in object file
[Warning] Skipping scanf, not found in object file
[Warning] Skipping sscanf, not found in object file
[Warning] Skipping fscanf, not found in object file
[Warning] Skipping scanf, not found in object file
[Warning] Skipping sscanf, not found in object file
[Warning] Skipping vfscanf, not found in object file
[Warning] Skipping vscanf, not found in object file
[Warning] Skipping vsscanf, not found in object file
[Warning] Skipping vfscanf, not found in object file
[Warning] Skipping vscanf, not found in object file
[Warning] Skipping vsscanf, not found in object file
[Warning] Skipping fgetc, not found in object file
[Warning] Skipping getc, not found in object file
[Warning] Skipping getchar, not found in object file
[Warning] Skipping getc_unlocked, not found in object file
[Warning] Skipping getchar_unlocked, not found in object file
[Warning] Skipping fgetc_unlocked, not found in object file
[Warning] Skipping putc, not found in object file
[Warning] Skipping putchar, not found in object file
[Warning] Skipping fputc_unlocked, not found in object file
[Warning] Skipping putc_unlocked, not found in object file
[Warning] Skipping putchar_unlocked, not found in object file
[Warning] Skipping getw, not found in object file
[Warning] Skipping putw, not found in object file
[Warning] Skipping gets, not found in object file
[Warning] Skipping __getdelim, not found in object file
[Warning] Skipping getdelim, not found in object file
[Warning] Skipping getline, not found in object file
[Warning] Skipping puts, not found in object file
[Warning] Skipping ungetc, not found in object file
[Warning] Skipping fread_unlocked, not found in object file
[Warning] Skipping fwrite_unlocked, not found in object file
[Warning] Skipping rewind, not found in object file
[Warning] Skipping fseeko, not found in object file
[Warning] Skipping ftello, not found in object file
[Warning] Skipping fgetpos, not found in object file
[Warning] Skipping fsetpos, not found in object file
[Warning] Skipping clearerr, not found in object file
[Warning] Skipping ferror, not found in object file
[Warning] Skipping clearerr_unlocked, not found in object file
[Warning] Skipping feof_unlocked, not found in object file
[Warning] Skipping ferror_unlocked, not found in object file
[Warning] Skipping fileno_unlocked, not found in object file
[Warning] Skipping pclose, not found in object file
[Warning] Skipping popen, not found in object file
[Warning] Skipping ctermid, not found in object file
[Warning] Skipping flockfile, not found in object file
[Warning] Skipping ftrylockfile, not found in object file
[Warning] Skipping funlockfile, not found in object file
[Warning] Skipping __uflow, not found in object file
[Warning] Skipping __overflow, not found in object file
[Warning] Skipping clock, not found in object file
[Warning] Skipping difftime, not found in object file
[Warning] Skipping mktime, not found in object file
[Warning] Skipping strftime_l, not found in object file
[Warning] Skipping gmtime, not found in object file
[Warning] Skipping localtime, not found in object file
[Warning] Skipping localtime_r, not found in object file
[Warning] Skipping asctime, not found in object file
[Warning] Skipping ctime, not found in object file
[Warning] Skipping asctime_r, not found in object file
[Warning] Skipping ctime_r, not found in object file
[Warning] Skipping __tzname, not found in object file
[Warning] Skipping __daylight, not found in object file
[Warning] Skipping __timezone, not found in object file
[Warning] Skipping tzname, not found in object file
[Warning] Skipping tzset, not found in object file
[Warning] Skipping daylight, not found in object file
[Warning] Skipping timezone, not found in object file
[Warning] Skipping timegm, not found in object file
[Warning] Skipping timelocal, not found in object file
[Warning] Skipping dysize, not found in object file
[Warning] Skipping nanosleep, not found in object file
[Warning] Skipping clock_getres, not found in object file
[Warning] Skipping clock_settime, not found in object file
[Warning] Skipping clock_nanosleep, not found in object file
[Warning] Skipping clock_getcpuclockid, not found in object file
[Warning] Skipping timer_create, not found in object file
[Warning] Skipping timer_delete, not found in object file
[Warning] Skipping timer_settime, not found in object file
[Warning] Skipping timer_gettime, not found in object file
[Warning] Skipping timer_getoverrun, not found in object file
[Warning] Skipping settimeofday, not found in object file
[Warning] Skipping adjtime, not found in object file
[Warning] Skipping getitimer, not found in object file
[Warning] Skipping setitimer, not found in object file
[Warning] Skipping utimes, not found in object file
[Warning] Skipping lutimes, not found in object file
[Warning] Skipping futimes, not found in object file
[Warning] __cfloat128 could not be compiled: _Complex float is not supported by ext/ffi
```

**Comment by bwoebi** [comment]
Yes, that's expected as of now. You're generating headers against libcurl.so, not against libc.so.
This is basically the next thing on the TODO - that FFIMe looks at the libraries the given library is linked against, then traverses them all.

For now - if you need curl and libc functions, you'll have to generate two files.

**Comment by cayolblake** [comment]
@bwoebi Ah I understand.. What would the generate/usage code would look like if I wanna do both? Since I can't use them apart if I'm going to consume the libcurl APIs!? 🤔 

Much appreciate your support big time!!

**Comment by bwoebi** [comment]
So, you'd just generate both, once with the headers you want to consume from curl, once with these you want to consume from libc.
And then you need to be aware which functions are only present in libc, and which only in curl.

Then you instantiate both and use the functions on the respective instance - and for non-primitive types you'd have to wrap and unwrap. It'll work, but it's not pretty. Hence I'm aiming at changing that sometime soon.

**Comment by cayolblake** [comment]
@bwoebi I'm not sure I totally grasp the sequence you mentioned.

If you can provide an example code on doing so would be great?

Also, if the sometime soon, is really soon, I guess we'll be waiting for it. :)
